### ISSUE TITLE
Simpson's paradox in regression?

### ISSUE THREAD

**Issue by sharonwsolis** [fishymary/git_collab#1]
@fishymary looks like there might be a problem in estimating the relationship. the figure created in the chunk code beginning in [L50](https://github.com/fishymary/git_collab/blob/master/docs/manuscript.Rmd#L50)

clear positive trend. perhaps we should fit three distinct lines?

**Comment by sharonwsolis** [comment]
actually it is this code chunk [L50-L59](https://github.com/fishymary/git_collab/blob/master/docs/manuscript.Rmd#L50-L59)

**Comment by fishymary** [comment]
Looks right. I can't address this right away, can you take care of it?
